### ISSUE TITLE
Flipped IAS/TAS

### ISSUE THREAD

**Issue by nebriv** [nebriv/VTOLVR-TacviewLogger#15]
User reports IAS/TAS are flipped.

**Comment by Shinrar** [comment]
Test 1:
10k Altitude (autopilot hold)
Autopilot Heading Hold
400 KTAS (autopilot hold)

![screenshot21](https://user-images.githubusercontent.com/75647195/101418999-10659800-38bd-11eb-9485-ad790486d782.png)
![screenshot23](https://user-images.githubusercontent.com/75647195/101419009-165b7900-38bd-11eb-96e8-b952fb1905a2.png)
![image](https://user-images.githubusercontent.com/75647195/101419098-486cdb00-38bd-11eb-9907-a7bc07da018a.png)

[datalog.acmi.txt](https://github.com/nebriv/VTOLVR-TacviewLogger/files/5655903/datalog.acmi.txt)

(More tests to follow, including high altitude and low altitude mach)

**Comment by Shinrar** [comment]
Test 2:
Altitude, 45,000 feet (approximately)
Speed, Mach 1 (575 knots true air speed, as displayed in HUD)

![screenshot26](https://user-images.githubusercontent.com/75647195/101700840-bd6e1b00-3a4b-11eb-92d3-d39554e3e154.png)

![image](https://user-images.githubusercontent.com/75647195/101700911-e0003400-3a4b-11eb-8ef3-667ea9d3e8a4.png)
Tacview displays:
KIAS 575
Mach .59
KTAS 340

[datalog.acmi.txt](https://github.com/nebriv/VTOLVR-TacviewLogger/files/5669318/datalog.acmi.txt)
[(Player log not needed but why not, right?)](https://github.com/nebriv/VTOLVR-TacviewLogger/files/5669320/Player.log)

**Comment by nebriv** [comment]
Thanks! Fixed in f24f556ba17827fd5cd6dedd195a6a25fba24c33
