### ISSUE TITLE
Height Map generation fails on some maps

### ISSUE THREAD

**Issue by nebriv** [nebriv/VTOLVR-TacviewLogger#16]

**Comment by Shinrar** [comment]
Tested Scenario:
https://steamcommunity.com/sharedfiles/filedetails/?id=1865441273&searchtext=

Verified Tacview functioning by testing known-to-work scenario first.

[Player.log](https://github.com/nebriv/VTOLVR-TacviewLogger/files/5655827/Player.log)
[datalog.acmi.txt](https://github.com/nebriv/VTOLVR-TacviewLogger/files/5655843/datalog.acmi.txt)

Relevant line to search for:
VTOL VR Tacview Data Logger - Looking for Map ID starwarsCanyon
(Error thrown below line)

**Comment by Shinrar** [comment]
No height map generated.  Not acmi generated aside from header.
