### ISSUE TITLE
Time out of sync for first portion of recording

### ISSUE THREAD

**Issue by Shinrar** [nebriv/VTOLVR-TacviewLogger#18]
The "delay" time seems to correlate to the time from mod loading, to the time where the mission begins.  Example attached:

Mission begin time: 13:04:23
Initial telemetry - 10.4 knots True Airspeed.
Fluxuates widely until: 13:06:20

The approximate two minute delay seems to be equal to the time it took to set up (loadout and mission load) from loading the mod.

File attached
[datalog.acmi.txt](https://github.com/nebriv/VTOLVR-TacviewLogger/files/5655862/datalog.acmi.txt)

**Comment by nebriv** [comment]
@Shinrar I'm initially seeing a 2 second fluctuation in data. I believe the TAS/IAS flip bug was also a part of this issue.

To fix this issue I've simply added a 2 second delay before capturing data to let the game stabilize. Fixed with 69c06a6f14afd674e5fe02d2904e329fef37f124.
