### ISSUE TITLE
Some models have incorrect orientation

### ISSUE THREAD

**Issue by Shinrar** [nebriv/VTOLVR-TacviewLogger#19]
Example ASF-30 (Correct orientation)
![image](https://user-images.githubusercontent.com/75647195/101491038-3af13880-3931-11eb-8ef2-12ee98ce23b8.png)

Example ASF-33 (Incorrect orientation)
![image](https://user-images.githubusercontent.com/75647195/101491397-adfaaf00-3931-11eb-9222-9fe6f952ba9c.png)

Example AIM-120 (incorrect orientation) (missile is tracking a target to the left, not the right, for context.  This is only sometimes, for some reason.
![image](https://user-images.githubusercontent.com/75647195/101491746-1c3f7180-3932-11eb-9779-ab59d58a8d17.png)
![image](https://user-images.githubusercontent.com/75647195/101491636-fc0fb280-3931-11eb-95be-729c0e7ee9c4.png)
![image](https://user-images.githubusercontent.com/75647195/101491784-295c6080-3932-11eb-8192-c300bd8ddc91.png)
(Last image to confirm that both targets it wants to hit, are left, and going left, and no one is going right)
![image](https://user-images.githubusercontent.com/75647195/101491925-4f820080-3932-11eb-9810-52730331c4cb.png)

Example KC-49 (incorrect orientation)
![image](https://user-images.githubusercontent.com/75647195/101491263-899ed280-3931-11eb-99a2-4b25b72c5a99.png)

Intention:
Create a map with one of every unit to confirm all unit orientations for debugging purposes.  Missiles and munitions will be more difficult, but we must perceiver.

**Comment by nebriv** [comment]
@Shinrar My KC-49 flies in the correct orientation - can you send your acmi for that one?

ASF-33 fixed in 4af84e9d79da6866d48dc1aa20b11a2a10b742f6.

**Comment by Shinrar** [comment]
Reply to above:
Did another one with 2.4rc1
![image](https://user-images.githubusercontent.com/75647195/101998678-5e0a4800-3ca3-11eb-9a92-2cecc334e496.png)
[datalog.acmi.txt](https://github.com/nebriv/VTOLVR-TacviewLogger/files/5683881/datalog.acmi.txt)

If it is correct on yours, I will attempt to reinstall the assets.

**Comment by nebriv** [comment]
Yep - you'll need to copy the assets out and replace the current ones

**Comment by Shinrar** [comment]
Replaced assets and resolved.

**Comment by TytanRock** [comment]
@nebriv
My Carrier and Escort ships appear to be facing the incorrect direction after updating the assets. Would you mind double checking it on your end?
[datalog.acmi.zip](https://github.com/nebriv/VTOLVR-TacviewLogger/files/5727408/datalog.acmi.zip)
![image](https://user-images.githubusercontent.com/13025939/102841791-96143800-43d3-11eb-8895-42439e70a766.png)

**Comment by fern996** [comment]
Having this issue too.
