### ISSUE TITLE
Multiplayer Update

### ISSUE THREAD

**Issue by 5o6** [nebriv/VTOLVR-TacviewLogger#27]
Description:
No data is exported from official multiplayer flight scenes. No data is exported from singleplayer flight scenes.

Steps to reproduce:
1. Run VTOL VR from mod loader with only Tacview Data Logger loaded. 2. Load Tacview Data Logger. 3. Launch multiplayer PvP mission. 4. End Mission 5. Exit Game
[TEMP.zip](https://github.com/nebriv/VTOLVR-TacviewLogger/files/7917460/TEMP.zip)

**Comment by nebriv** [comment]
Thanks for this report - I'll see if I can find sometime to look into this.

**Comment by nebriv** [comment]
@5o6 Looking at your player log it doesn't appear as though the Tacview mod or the modloader actually were loaded into the game. Can you give it another go and re-upload a fresh player log?

**Comment by 5o6** [comment]
Will do, give me a few minutes

**Comment by 5o6** [comment]
See attached log and acmi files (one for multiplayer and one for single player)
[ZIP.zip](https://github.com/nebriv/VTOLVR-TacviewLogger/files/7919118/ZIP.zip)
.

**Comment by nebriv** [comment]
@5o6 are you on a discord somewhere I can reach you - the vtol vr modding or official vtol vr server? Just ping me @nebriv.

**Comment by 5o6** [comment]
will do

**Comment by nebriv** [comment]
Resolved with 5a974a11f36490b89d3f39f084c985540af0b709
